// Code generated by protoc-gen-go. DO NOT EDIT.
// source: identity-service.proto

package lasagna_identity_service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	FirstName            string   `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Password             string   `protobuf:"bytes,6,opt,name=password,proto3" json:"password,omitempty"`
	Token                string   `protobuf:"bytes,7,opt,name=token,proto3" json:"token,omitempty"`
	Budget               uint32   `protobuf:"varint,8,opt,name=budget,proto3" json:"budget,omitempty"`
	Skill                uint32   `protobuf:"varint,9,opt,name=skill,proto3" json:"skill,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_service_8e653799c6387f47, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *User) GetBudget() uint32 {
	if m != nil {
		return m.Budget
	}
	return 0
}

func (m *User) GetSkill() uint32 {
	if m != nil {
		return m.Skill
	}
	return 0
}

type Response struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Users                []*User  `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Errors               []*Error `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	Token                *Token   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_service_8e653799c6387f47, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Response) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Response) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

func (m *Response) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_service_8e653799c6387f47, []int{2}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	Errors               []*Error `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_service_8e653799c6387f47, []int{3}
}
func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (dst *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(dst, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Token) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *Token) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_identity_service_8e653799c6387f47, []int{4}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (dst *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(dst, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "lasagna.identity.service.User")
	proto.RegisterType((*Response)(nil), "lasagna.identity.service.Response")
	proto.RegisterType((*Request)(nil), "lasagna.identity.service.Request")
	proto.RegisterType((*Token)(nil), "lasagna.identity.service.Token")
	proto.RegisterType((*Error)(nil), "lasagna.identity.service.Error")
}

func init() {
	proto.RegisterFile("identity-service.proto", fileDescriptor_identity_service_8e653799c6387f47)
}

var fileDescriptor_identity_service_8e653799c6387f47 = []byte{
	// 441 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x54, 0x4d, 0x6b, 0x14, 0x41,
	0x10, 0x75, 0x76, 0x3e, 0x32, 0x53, 0x21, 0x0a, 0x85, 0x84, 0x26, 0xa2, 0xc6, 0x39, 0x79, 0x71,
	0x0e, 0xab, 0xe2, 0xc9, 0x43, 0x10, 0x91, 0x20, 0x04, 0x9c, 0xa8, 0x57, 0x99, 0xec, 0x94, 0xb1,
	0x49, 0x67, 0x7a, 0xed, 0xee, 0x8d, 0xf8, 0x73, 0xfc, 0x6f, 0x9e, 0xfc, 0x15, 0x76, 0x57, 0xcf,
	0x62, 0x50, 0xf6, 0x03, 0xc9, 0x69, 0xba, 0xde, 0x7b, 0x55, 0x5d, 0xfd, 0xaa, 0x18, 0xd8, 0x97,
	0x3d, 0x0d, 0x4e, 0xba, 0xef, 0x4f, 0x2c, 0x99, 0x2b, 0x39, 0xa3, 0x66, 0x6e, 0xb4, 0xd3, 0x28,
	0x54, 0x67, 0xbb, 0xf3, 0xa1, 0x6b, 0x96, 0x7c, 0x33, 0xf2, 0xf5, 0xaf, 0x04, 0xb2, 0x0f, 0x3e,
	0xc0, 0xdb, 0x30, 0x91, 0xbd, 0x48, 0x0e, 0x93, 0xc7, 0x55, 0xeb, 0x4f, 0x78, 0x17, 0x72, 0xba,
	0xec, 0xa4, 0x12, 0x13, 0x86, 0x62, 0x80, 0x87, 0xb0, 0xdb, 0x93, 0x9d, 0x19, 0x39, 0x77, 0x52,
	0x0f, 0x22, 0x65, 0xee, 0x3a, 0x84, 0xf7, 0x01, 0x3e, 0x4b, 0x63, 0xdd, 0xa7, 0xa1, 0xbb, 0x24,
	0x91, 0xb1, 0xa0, 0x62, 0xe4, 0xc4, 0x03, 0x78, 0x0f, 0x2a, 0xdf, 0xcb, 0xc8, 0xe6, 0xcc, 0x96,
	0x01, 0x60, 0xf2, 0x00, 0xca, 0x79, 0x67, 0xed, 0x37, 0x6d, 0x7a, 0x51, 0x44, 0x6e, 0x19, 0x87,
	0x7e, 0x9c, 0xbe, 0xa0, 0x41, 0xec, 0xc4, 0x7e, 0x38, 0xc0, 0x7d, 0x28, 0xce, 0x16, 0xfd, 0x39,
	0x39, 0x51, 0x7a, 0x78, 0xaf, 0x1d, 0xa3, 0xa0, 0xb6, 0x17, 0x52, 0x29, 0x51, 0x31, 0x1c, 0x83,
	0xfa, 0x67, 0x02, 0x65, 0x4b, 0x76, 0xae, 0x07, 0x4b, 0x38, 0x85, 0x6c, 0xe1, 0x1f, 0xce, 0x4f,
	0xde, 0x9d, 0x3e, 0x68, 0x56, 0x59, 0xd4, 0x04, 0x7b, 0x5a, 0xd6, 0xe2, 0x33, 0xc8, 0xc3, 0xd7,
	0x7a, 0x53, 0xd2, 0x2d, 0x92, 0xa2, 0x18, 0x5f, 0x40, 0x41, 0xc6, 0x68, 0x9f, 0x96, 0x72, 0xda,
	0xc3, 0xd5, 0x69, 0xaf, 0x83, 0xae, 0x1d, 0xe5, 0xf8, 0x7c, 0xf9, 0xe6, 0x8c, 0x7b, 0x5c, 0x93,
	0xf7, 0x3e, 0xc8, 0x46, 0x53, 0xea, 0x0a, 0x76, 0x5a, 0xfa, 0xba, 0x20, 0xeb, 0x6a, 0x05, 0x39,
	0x53, 0x7f, 0xec, 0x4b, 0xae, 0xdb, 0xe7, 0xd1, 0xab, 0x4e, 0xf9, 0xb9, 0x87, 0x21, 0x97, 0x6d,
	0x0c, 0xfe, 0xbb, 0xdf, 0xfa, 0x25, 0xe4, 0x0c, 0x20, 0x42, 0x36, 0xd3, 0x3d, 0xf1, 0x65, 0x79,
	0xcb, 0xe7, 0xbf, 0x57, 0x67, 0xf2, 0xcf, 0xea, 0x4c, 0x7f, 0xa4, 0x70, 0xe7, 0x78, 0xbc, 0xe1,
	0x34, 0x5e, 0x80, 0x27, 0x50, 0xbc, 0x32, 0xd4, 0x39, 0xc2, 0x0d, 0x66, 0x1f, 0xd4, 0xab, 0xf9,
	0xe5, 0xcc, 0xeb, 0x5b, 0xf8, 0x16, 0xd2, 0x37, 0x7e, 0x3f, 0x6e, 0xa6, 0xd8, 0x3b, 0x28, 0x7c,
	0xb1, 0x23, 0xa5, 0xf0, 0xd1, 0x3a, 0x3d, 0x8f, 0x62, 0xcb, 0x92, 0xc7, 0x90, 0x1d, 0x2d, 0xdc,
	0x97, 0x8d, 0x0d, 0x6e, 0xda, 0x05, 0x5f, 0xea, 0x14, 0xf6, 0x3e, 0x86, 0x79, 0x7a, 0xf3, 0xe2,
	0x0e, 0x6c, 0xca, 0xd9, 0xa2, 0xe8, 0x59, 0xc1, 0x3f, 0x94, 0xa7, 0xbf, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x3c, 0x39, 0x0b, 0xe6, 0x6a, 0x04, 0x00, 0x00,
}
