// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal-recipes-service.proto

package internal_recipes_service

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Recipe struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Recipe) Reset()         { *m = Recipe{} }
func (m *Recipe) String() string { return proto.CompactTextString(m) }
func (*Recipe) ProtoMessage()    {}
func (*Recipe) Descriptor() ([]byte, []int) {
	return fileDescriptor_459e21869af81ec2, []int{0}
}

func (m *Recipe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Recipe.Unmarshal(m, b)
}
func (m *Recipe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Recipe.Marshal(b, m, deterministic)
}
func (m *Recipe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Recipe.Merge(m, src)
}
func (m *Recipe) XXX_Size() int {
	return xxx_messageInfo_Recipe.Size(m)
}
func (m *Recipe) XXX_DiscardUnknown() {
	xxx_messageInfo_Recipe.DiscardUnknown(m)
}

var xxx_messageInfo_Recipe proto.InternalMessageInfo

func (m *Recipe) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Recipe) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Recipe) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type GetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_459e21869af81ec2, []int{1}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

type Response struct {
	Created              bool      `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Recipe               *Recipe   `protobuf:"bytes,2,opt,name=recipe,proto3" json:"recipe,omitempty"`
	Recipes              []*Recipe `protobuf:"bytes,3,rep,name=recipes,proto3" json:"recipes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_459e21869af81ec2, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetRecipe() *Recipe {
	if m != nil {
		return m.Recipe
	}
	return nil
}

func (m *Response) GetRecipes() []*Recipe {
	if m != nil {
		return m.Recipes
	}
	return nil
}

func init() {
	proto.RegisterType((*Recipe)(nil), "lasagna.srv.internal.recipes.service.Recipe")
	proto.RegisterType((*GetRequest)(nil), "lasagna.srv.internal.recipes.service.GetRequest")
	proto.RegisterType((*Response)(nil), "lasagna.srv.internal.recipes.service.Response")
}

func init() { proto.RegisterFile("internal-recipes-service.proto", fileDescriptor_459e21869af81ec2) }

var fileDescriptor_459e21869af81ec2 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x31, 0x4b, 0x3c, 0x31,
	0x10, 0xc5, 0xff, 0xbb, 0xfb, 0x67, 0xef, 0x9c, 0x3b, 0x2c, 0xa6, 0x90, 0x70, 0x85, 0x2c, 0x8b,
	0x85, 0x85, 0x17, 0xe4, 0xfc, 0x06, 0x2a, 0x8a, 0x8d, 0x45, 0xec, 0xec, 0xe2, 0xee, 0x20, 0x81,
	0x33, 0x1b, 0x33, 0xf1, 0x3e, 0x98, 0x1f, 0xcf, 0x4a, 0x48, 0xb2, 0x68, 0x23, 0xec, 0x76, 0xc9,
	0xcc, 0xef, 0xe5, 0x3d, 0x1e, 0x81, 0x53, 0x63, 0x03, 0x79, 0xab, 0xf7, 0x5b, 0x4f, 0x9d, 0x71,
	0xc4, 0x5b, 0x26, 0x7f, 0x30, 0x1d, 0x49, 0xe7, 0x87, 0x30, 0xe0, 0xd9, 0x5e, 0xb3, 0x7e, 0xb5,
	0x5a, 0xb2, 0x3f, 0xc8, 0x91, 0x95, 0x99, 0x95, 0x99, 0x6d, 0x1f, 0xa1, 0x56, 0x71, 0x84, 0xc7,
	0x50, 0x9a, 0x5e, 0x14, 0x4d, 0x71, 0x7e, 0xa4, 0x4a, 0xd3, 0x23, 0xc2, 0x7f, 0xab, 0xdf, 0x48,
	0x94, 0x71, 0x12, 0xcf, 0xd8, 0xc0, 0xaa, 0x27, 0xee, 0xbc, 0x71, 0xc1, 0x0c, 0x56, 0x54, 0x71,
	0xf5, 0x7b, 0xd4, 0xae, 0x01, 0xee, 0x29, 0x28, 0x7a, 0xff, 0x20, 0x0e, 0xed, 0x67, 0x01, 0x4b,
	0x45, 0xec, 0x06, 0xcb, 0x84, 0x02, 0x16, 0x9d, 0x27, 0x1d, 0x28, 0xb9, 0x2c, 0xd5, 0x78, 0xc5,
	0x5b, 0xa8, 0x53, 0xae, 0x68, 0xb6, 0xda, 0x5d, 0xc8, 0x29, 0xd9, 0x65, 0x0a, 0xae, 0xb2, 0x16,
	0xef, 0x60, 0x91, 0x09, 0x51, 0x35, 0xd5, 0xec, 0x67, 0x46, 0xf1, 0xee, 0xab, 0x80, 0x93, 0x87,
	0x0c, 0xa7, 0x1d, 0x3f, 0x25, 0x14, 0x2d, 0xac, 0x6f, 0x62, 0xe6, 0xdc, 0xd9, 0x2c, 0x87, 0x8d,
	0x9c, 0x4a, 0xa7, 0xc2, 0xda, 0x7f, 0xe8, 0x72, 0x9b, 0x11, 0xc0, 0xcb, 0x69, 0xfa, 0x9f, 0xfe,
	0xe7, 0x3b, 0x5e, 0x6f, 0x9e, 0xc5, 0x5f, 0xd8, 0x4b, 0x1d, 0x3f, 0xd6, 0xd5, 0x77, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x64, 0xcf, 0xaa, 0x5d, 0x7a, 0x02, 0x00, 0x00,
}
