// Generated by protoc-gen-twirp_typescript. DO NOT EDIT
import {lasagna} from './internal-recipes-service.pb';
import {createTwirpAdapter} from 'pbjs-twirp';
import Axios from 'axios';

const getServiceMethodName = (fn: any): string => {
	if (fn === lasagna.srv.internal.recipes.service.InternalRecipesService.prototype.createRecipe) {
		return 'CreateRecipe';
    }
	if (fn === lasagna.srv.internal.recipes.service.InternalRecipesService.prototype.getRecipes) {
		return 'GetRecipes';
    }

    throw new Error('Unknown Method');
};


export const InternalRecipesServicePathPrefix = '/twirp/lasagna.srv.internal.recipes.service.InternalRecipesService/';

export const createInternalRecipesService = (baseURL: string): lasagna.srv.internal.recipes.service.InternalRecipesService => {
	const axios = Axios.create({
        baseURL: baseURL + InternalRecipesServicePathPrefix,
        headers: {
          Accept: 'application/protobuf'
        }
    });

    return lasagna.srv.internal.recipes.service.InternalRecipesService.create(createTwirpAdapter(axios, getServiceMethodName));
};
