kind: pipeline
name: default

steps:
  - name: test
    image: compose:1.23.2
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker-compose up -f /drone/src/docker-compose.yml
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
