kind: pipeline
name: default

steps:
  - name: publish
    image: docker/compose:1.23.2
    environment:
      DOCKER_USERNAME:
        from_secret: DOCKER_USERNAME
      DOCKER_PASSWORD:
        from_secret: DOCKER_PASSWORD
      DB_USER:
        from_secret: DB_USER
      DB_PASSWORD:
        from_secret: DB_PASSWORD
      DB_ROOT_PASSWORD:
        from_secret: DB_ROOT_PASSWORD
      JWT_SECRET:
        from_secret: JWT_SECRET
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker-compose build
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker-compose push
      - docker-compose up --force-recreate -d
    when:
      branch:
        - master
      event:
        - push
trigger:
  event:
    - push
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
