version: "3.7"

services:
# Internal Recipes Service
  internal-recipes-service:
    build:
      context: .
      dockerfile: ./internal-recipes-service/Dockerfile
    image: edwincloud/internal-recipes-service
    ports:
      - "50051:50051"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      SERVICE_ADDRESS: ":50051"
      DB_HOST: "recipes-db"
      DB_PORT: "3307"
      DB_NAME: "recipes"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
    networks:
      - my_net
    depends_on:
      - recipes-db
# Internal Recipes Service Database
  recipes-db:
    image: mariadb:latest
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
    volumes:
      - recipes-data:/var/lib/mysql
    ports:
      - "3306:3306"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "recipes"   
    networks:
      - my_net
# Identity Service
  identity-service:
    build:
      context: .
      dockerfile: ./identity-service/Dockerfile
    image: edwincloud/identity-service
    ports:
      - "50052:50052"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      SERVICE_ADDRESS: ":50052"
      DB_HOST: "identity-db"
      DB_PORT: "3307"
      DB_NAME: "users"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      JWT_SECRET: "${JWT_SECRET}"
    networks:
      - my_net
    depends_on:
      - identity-db
# Identity Service Database
  identity-db:
    image: mariadb:latest
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
    volumes:
      - identity-data:/var/lib/mysql
    ports:
      - "3307:3306"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "users"   
    networks:
      - my_net
# API Service
  api-service:
    build:
      context: .
      dockerfile: ./api-service/Dockerfile
    image: edwincloud/api-service
    ports:
      - "8080:8080"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      RECIPES_SERVICE_ADDRESS: "internal-recipes-service:50051"
      IDENTITY_SERVICE_ADDRESS: "identity-service:50052"
    depends_on:
      - internal-recipes-service
    networks:
      - my_net
# DRONE SERVER
  drone-server:
    image: drone/drone:1
    ports:
      - "80:80"
      - "9000:9000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      DRONE_GITHUB_CLIENT_ID: "${DRONE_GITHUB_CLIENT_ID}"
      DRONE_GITHUB_CLIENT_SECRET: "${DRONE_GITHUB_CLIENT_SECRET}"
      DRONE_SERVER_HOST: "localhost"
      DRONE_SERVER_PROTO: "http"
      DRONE_RPC_SECRET: "${DRONE_RPC_SECRET}"
    networks:
      - my_net
    volumes:
      - /var/lib/drone:/data
# DRONE AGENT
  drone-agent:
    image: drone/agent:1
    command: agent
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - drone-server
    environment:
      DRONE_RPC_SERVER: "drone-server:9000"
      DRONE_RPC_SECRET: "${DRONE_RPC_SECRET}"
    networks:
      - my_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

# Networks Configuration
networks:
  my_net:
    driver: overlay

# Volumes Configuration
volumes:
  recipes-data:
  identity-data: