version: '3.7'

services:

  internal-recipes-service:
    build: ./internal-recipes-service
    ports: 
      - 50051:50051
    environment: 
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"

  api-service:
    build: ./api-service
    ports:
      - 127.0.0.1:9000:9000
    environment:
      MICRO_REGISTRY: "mdns"
      PORT: ":9000"
    depends_on:
      - internal-recipes-service
      - identity-service
  
  database:
    image: postgres
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_PASSWORD: "supersecretpassword"
  
  identity-service:
    build: ./identity-service
    ports: 
      - 50052:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "database"
      DB_USER: "postgres"
      DB_NAME: "users"
      DB_PASSWORD: "supersecretpassword"
    depends_on:
      - database