version: "3.7"

services:
  internal-recipes-service:
    build:
      context: .
      dockerfile: ./internal-recipes-service/Dockerfile
    image: edwincloud/internal-recipes-service
    ports:
      - "50051:50051"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      SERVICE_ADDRESS: "50051"
    networks:
      - my_net
    depends_on:
      - recipes-db
  recipes-db:
    image: mariadb:latest
    volumes:
      - recipes-data:/var/lib/mysql
    ports:
      - "3306:3306"
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    environment:
      MYSQL_ROOT_PASSWORD: "secretpassword"
      MYSQL_DATABASE: "recipes"
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "password"
    networks:
      - my_net
  api-service:
    build:
      context: .
      dockerfile: ./api-service/Dockerfile
    image: edwincloud/api-service
    ports:
      - "80:8080"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      RECIPES_SERVICE_ADDRESS: "internal-recipes-service:50051"
    depends_on:
      - internal-recipes-service
    networks:
      - my_net

networks:
  my_net:
    driver: overlay

volumes:
  recipes-data: