version: "3.7"

configs:
  cluster_config:
    file: ./.env

services:
  internal-recipes-service:
    build: ./internal-recipes-service
    image: edwincloud/internal-recipes-service
    ports:
      - 50051:50051
    deploy:
      replicas: 1
    configs:
      - cluster_config
  identity-database:
    image: postgres:alpine
    ports:
      - 5432:5432
    deploy:
      replicas: 1
    configs:
      - cluster_config
  identity-service:
    build: ./identity-service
    image: edwincloud/identity-service
    ports:
      - 50052:50051
    deploy:
      replicas: 1
    configs:
      - cluster_config
    depends_on:
      - identity-database
  api-gateway:
    image: microhq/micro
    ports:
      - 8080:8080
    command: api
    deploy:
      replicas: 1
    configs:
      - cluster_config
    depends_on:
      - internal-recipes-service
      - identity-service
