version: '3.7'

services:

  internal-recipes-service:
    build: ./internal-recipes-service
    ports: 
      - 127.0.0.1:50051:50051
    environment: 
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"

  api-service:
    build: ./api-service
    environment:
      MICRO_REGISTRY: "mdns"
    depends_on:
      - internal-recipes-service