version: "3.7"

services:
  internal-recipes-service:
    build:
      context: .
      dockerfile: ./internal-recipes-service/Dockerfile
    image: edwincloud/internal-recipes-service
    ports:
      - "50051:50051"
    deploy:
      replicas: 1
    environment:
      SERVICE_ADDRESS: "internal-recipes-service:50051"
    networks:
      - my_net
  # identity-database:
  #   image: postgres:alpine
  #   ports:
  #     - "5432:5432"
  #   deploy:
  #     replicas: 1
  #   environment:
  #     POSTGRES_PASSWORD: "supersecretpassword"
  #     POSTGRES_DB: "users"
  #   networks:
  #     - my_net
  # identity-service:
  #   build:
  #     context: .
  #     dockerfile: ./identity-service/Dockerfile
  #   image: edwincloud/identity-service
  #   ports:
  #     - "50052:50052"
  #   deploy:
  #     replicas: 1
  #   environment:
  #     SERVICE_ADDRESS: "127.0.0.1:50052"
  #     DB_HOST: "identity-database"
  #     DB_PORT: "5432"
  #     DB_USER: "postgres"
  #     DB_NAME: "users"
  #     DB_PASSWORD: "supersecretpassword"
  #     JWT_SECRET: "supersecret"
  #   depends_on:
  #     - identity-database
  #   networks:
  #     - my_net
  api-service:
    build:
      context: .
      dockerfile: ./api-service/Dockerfile
    image: edwincloud/api-service
    ports:
      - "80:8080"
    deploy:
      replicas: 1
    environment:
      RECIPES_SERVICE_ADDRESS: "internal-recipes-service:50051"
    depends_on:
      - internal-recipes-service
    networks:
      - my_net

networks:
  my_net: 