version: '3.7'

services:

  internal-recipes-service:
    build:
      context: .
      dockerfile: ./internal-recipes-service/Dockerfile
    ports: 
      - 50051:50051
    environment: 
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"

  # api-service:
  #   build:
  #     context: .
  #     dockerfile: ./api-service/Dockerfile
  #   ports:
  #     - 127.0.0.1:9000:9000
  #   environment:
  #     MICRO_REGISTRY: "mdns"
  #     PORT: ":9000"
  #   depends_on:
  #     - internal-recipes-service
  #     - identity-service
  
  database:
    image: postgres:alpine
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_PASSWORD: "supersecretpassword"
      POSTGRES_DB: "users"
  identity-service:
    build:
      context: .
      dockerfile: ./identity-service/Dockerfile
    ports: 
      - 50052:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "database"
      DB_USER: "postgres"
      DB_NAME: "users"
      DB_PASSWORD: "supersecretpassword"
      JWT_SECRET: "supersecret"
    depends_on:
      - database
  api-gateway:
    image: microhq/micro
    ports:
      - 127.0.0.1:8080:8080
    command: api
    environment:
      MICRO_REGISTRY: "mdns"
      MICRO_ADDRESS: ":50051"
      MICRO_API_NAMESPACE: "lasagna.api"
      MICRO_API_HANDLER: "rpc"
      MICRO_API_ADDRESS: "0.0.0.0:8080"
      MICRO_ENABLE_STATS: "true"
    depends_on:
      - internal-recipes-service
      - identity-service